---
# tasks file for roles/webserver

- name: Install Nginx package
  yum:
    name: nginx
  become: true

- name: Enable Nginx service
  service:
    name: nginx
    enabled: true
    state: started
  become: true
